### ISSUE TITLE
Use uinput on Linux

### ISSUE THREAD

**Issue by kitlith** [smasherprog/input_lite#1]
It may be desirable (especially with people moving to stuff like Wayland) to go through the kernel via uinput so that there is no runtime dependency on X11, making this work on systems that don't use X11.

libevdev has some [wrappers](https://www.freedesktop.org/software/libevdev/doc/latest/group__uinput.html) for using uinput, but you can totally use it [directly](http://lkcl.net/software/uinput/).

**Comment by smasherprog** [comment]
awesome thanks for this info! Ill work on implementing it.

**Comment by kitlith** [comment]
oh, appearantly it doesn't work well with multiuser systems w/ multiple X11 sessions, and can be a bit of a keylogger risk?

more research would probably be a good thing.
